title: Swirl
description: Ship a website, get ice cream!
url: https://swirl.hackclub.com
baseurl: ""

# Build settings
encoding: UTF-8

is_individual_submissions_open: false

# Files/dirs that should not be copied into the built site
exclude:
  - README.md
  - scripts/
  - Gemfile
  - Gemfile.lock
  - .prettierrc
  - vendor/
  - .idea/
